version: '3.4'

services:
  tiendademicroservicios.api.autor:
    image: ${DOCKER_REGISTRY-}tiendademicroserviciosapiautor
    build:
      context: .
      dockerfile: TiendaDeMicroservicios.API.Autor/Dockerfile
  tiendademicroservicios.api.libro:
    image: ${DOCKER_REGISTRY-}tiendademicroserviciosapilibro
    build:
      context: .
      dockerfile: TiendaDeMicroservicios.API.Libro/Dockerfile

networks:
  default:
    external:
      name: microserviceNet
