version: '3.4'

services:
  tiendademicroservicios.api.autor:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "2218:80"

  tiendademicroservicios.api.libro:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "9957:80"


  tiendademicroservicios.api.carritodecompras:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - Services__Libros=http://tiendademicroservicios.api.libro
      - Services__Autores=http://tiendademicroservicios.api.autor
    ports:
      - "3748:80"

