version: '3.4'

services:
  tiendademicroservicios.api.autor:
    image: ${DOCKER_REGISTRY-}tiendademicroserviciosapiautor
    build:
      context: .
      dockerfile: TiendaDeMicroservicios.API.Autor/Dockerfile
  tiendademicroservicios.api.libro:
    image: ${DOCKER_REGISTRY-}tiendademicroserviciosapilibro
    build:
      context: .
      dockerfile: TiendaDeMicroservicios.API.Libro/Dockerfile

  tiendademicroservicios.api.carritodecompras:
    image: ${DOCKER_REGISTRY-}tiendademicroserviciosapicarritodecompras
    build:
      context: .
      dockerfile: TiendaDeMicroservicios.API.CarritoDeCompras/Dockerfile

  tiendademicroservicios.api.gateway:
    image: ${DOCKER_REGISTRY-}tiendademicroserviciosapigateway
    build:
      context: .
      dockerfile: TiendaDeMicroServicios.API.Gateway/Dockerfile

networks:
  default:
    external:
      name: microserviceNet


